### ISSUE TITLE
Class 'Webklex\PDFMerger\Providers\PDFMergerServiceProvider' not found

### ISSUE THREAD

**Issue by aldiazhar** [Webklex/laravel-pdfmerger#26]
Hi guys, I got this error but only in production. Package works fine on the staging or local. 

[2022-07-29 15:24:01] production.ERROR: Class 'Webklex\PDFMerger\Providers\PDFMergerServiceProvider' not found {"exception":"[object] (Error(code: 0): Class 'Webklex\\PDFMerger\\Providers\\PDFMergerServiceProvider' not found at /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208)
[stacktrace]
#0 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/bpmb/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/bpmb/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"}

**Comment by Webklex** [comment]
Hi @aldiazhar ,
have you updated the dependency inside your production environment?

Perhaps you have to run:
```php
composer update
```

Best regards,
